repos:
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: clang-format
        args: [--dry-run, --Werror]
        language: system
        types_or: [c++, c]

      - id: gersemi
        name: gersemi
        entry: gersemi
        args: [--check]
        language: system
        files: '(CMakeLists\.txt|\.cmake)$'
